import './globals.css'
import Navbar from './components/Navbar/Navbar'
import { pressStart2P } from './fonts/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>Poke App</title>
      </head>
      <body className={pressStart2P.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
